apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: chaos-sandbox
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: nginx
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        chaos: blast-at-dev-conf
    spec:
      containers:
        - image: nginx
          name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: protected-deployment
  namespace: chaos-sandbox
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sensitive-environment
  template:
    metadata:
      labels:
        app: sensitive-environment
    spec:
      containers:
        - image: nginx
          name: nginx
